name: Mypy 
on: [ push, pull_request ]
jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - run: pip install --upgrade pip
      - run: pip install mypy
      - run: mypy --strict
  