name: Semantic Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: windows-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set-up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Set-up Poetry
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: "1.8"

    - name: Install Poetry Project
      run: poetry install

    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}